services:
  backend:
    container_name: calc-backend
    build: ./backend
    ports: 
      - "8080:8080"
  frontend:
    container_name: calc-frontend
    build: ./frontend
    ports: 
      - "4173:4173"
    depends_on:
      - backend
